<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__2rLAUhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..2rLAUh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..2rLAUh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossierMedical' => ['privates', '.errored..service_locator..2rLAUh.App\\Entity\\DossierMedical', NULL, 'Cannot autowire service ".service_locator..2rLAUh": it needs an instance of "App\\Entity\\DossierMedical" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dossierMedical' => 'App\\Entity\\DossierMedical',
            'entityManager' => '?',
        ]);
    }
}
