<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5lojCK6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5lojCK6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5lojCK6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialite' => ['privates', '.errored..service_locator.5lojCK6.App\\Entity\\Specialite', NULL, 'Cannot autowire service ".service_locator.5lojCK6": it needs an instance of "App\\Entity\\Specialite" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'specialite' => 'App\\Entity\\Specialite',
            'entityManager' => '?',
        ]);
    }
}
