<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AJ5N4gyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJ5N4gy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AJ5N4gy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rDV' => ['privates', '.errored..service_locator.AJ5N4gy.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.AJ5N4gy": it needs an instance of "App\\Entity\\RDV" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'rDV' => 'App\\Entity\\RDV',
            'entityManager' => '?',
        ]);
    }
}
