<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nm_.mR6.App\Controller\ConsultationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nm_.mR6.App\\Controller\\ConsultationController::delete()'] = ($container->privates['.service_locator.nm_.mR6'] ?? $container->load('get_ServiceLocator_Nm_MR6Service'))->withContext('App\\Controller\\ConsultationController::delete()', $container);
    }
}
