<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossierMedicalControllerdeleteImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gPjv2Im.App\Controller\DossierMedicalController::deleteImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gPjv2Im.App\\Controller\\DossierMedicalController::deleteImage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.gPjv2Im.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator.gPjv2Im": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'image' => 'App\\Entity\\Image',
            'em' => '?',
        ]))->withContext('App\\Controller\\DossierMedicalController::deleteImage()', $container);
    }
}
