<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossierMedicalControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6IXWlsK.App\Controller\DossierMedicalController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6IXWlsK.App\\Controller\\DossierMedicalController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossierMedicalRepository' => ['privates', 'App\\Repository\\DossierMedicalRepository', 'getDossierMedicalRepositoryService', true],
        ], [
            'dossierMedicalRepository' => 'App\\Repository\\DossierMedicalRepository',
        ]))->withContext('App\\Controller\\DossierMedicalController::index()', $container);
    }
}
