<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PS4oLjV.App\Controller\ImageController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PS4oLjV.App\\Controller\\ImageController::delete()'] = ($container->privates['.service_locator.PS4oLjV'] ?? $container->load('get_ServiceLocator_PS4oLjVService'))->withContext('App\\Controller\\ImageController::delete()', $container);
    }
}
