<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gBs64Cz.App\Controller\ImageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gBs64Cz.App\\Controller\\ImageController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.gBs64Cz.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator.gBs64Cz": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".'],
        ], [
            'image' => 'App\\Entity\\Image',
        ]))->withContext('App\\Controller\\ImageController::show()', $container);
    }
}
