<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObservation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qH_w4.d.App\Entity\Observation' shared service.
     *
     * @return \App\Entity\Observation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qH_w4.d": it needs an instance of "App\\Entity\\Observation" but this type has been excluded in "config/services.yaml".');
    }
}
