<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObservationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LTWnpqq.App\Controller\ObservationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LTWnpqq.App\\Controller\\ObservationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'observationRepository' => ['privates', 'App\\Repository\\ObservationRepository', 'getObservationRepositoryService', true],
        ], [
            'observationRepository' => 'App\\Repository\\ObservationRepository',
        ]))->withContext('App\\Controller\\ObservationController::index()', $container);
    }
}
