<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescription2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e5xkiI7.App\Entity\Prescription' shared service.
     *
     * @return \App\Entity\Prescription
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e5xkiI7": it needs an instance of "App\\Entity\\Prescription" but this type has been excluded in "config/services.yaml".');
    }
}
