<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wR08iD0.App\Controller\RDVController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wR08iD0.App\\Controller\\RDVController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rDVRepository' => ['privates', 'App\\Repository\\RDVRepository', 'getRDVRepositoryService', true],
        ], [
            'rDVRepository' => 'App\\Repository\\RDVRepository',
        ]))->withContext('App\\Controller\\RDVController::index()', $container);
    }
}
