<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJ5N4gy.App\Controller\RDVController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AJ5N4gy'] ?? $container->load('get_ServiceLocator_AJ5N4gyService'));

        if (isset($container->privates['.service_locator.AJ5N4gy.App\\Controller\\RDVController::edit()'])) {
            return $container->privates['.service_locator.AJ5N4gy.App\\Controller\\RDVController::edit()'];
        }

        return $container->privates['.service_locator.AJ5N4gy.App\\Controller\\RDVController::edit()'] = $a->withContext('App\\Controller\\RDVController::edit()', $container);
    }
}
