<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AJ5N4gy.App\Entity\RDV' shared service.
     *
     * @return \App\Entity\RDV
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AJ5N4gy": it needs an instance of "App\\Entity\\RDV" but this type has been excluded in "config/services.yaml".');
    }
}
