<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialiteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5lojCK6.App\Controller\SpecialiteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.5lojCK6'] ?? $container->load('get_ServiceLocator_5lojCK6Service'));

        if (isset($container->privates['.service_locator.5lojCK6.App\\Controller\\SpecialiteController::edit()'])) {
            return $container->privates['.service_locator.5lojCK6.App\\Controller\\SpecialiteController::edit()'];
        }

        return $container->privates['.service_locator.5lojCK6.App\\Controller\\SpecialiteController::edit()'] = $a->withContext('App\\Controller\\SpecialiteController::edit()', $container);
    }
}
