<?php

namespace ContainerGUTyEW7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialiteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JwtP_Q8.App\Controller\SpecialiteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JwtP_Q8.App\\Controller\\SpecialiteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
        ], [
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
        ]))->withContext('App\\Controller\\SpecialiteController::index()', $container);
    }
}
