<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'date_naissance' => [parent::class, 'date_naissance', null, 16],
        "\0".parent::class."\0".'dossierMedical' => [parent::class, 'dossierMedical', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'genre' => [parent::class, 'genre', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null, 16],
        "\0".parent::class."\0".'medecin_rdvs' => [parent::class, 'medecin_rdvs', null, 16],
        "\0".parent::class."\0".'mes_medecins' => [parent::class, 'mes_medecins', null, 16],
        "\0".parent::class."\0".'mes_patients' => [parent::class, 'mes_patients', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'numero_secu' => [parent::class, 'numero_secu', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'patient_rdvs' => [parent::class, 'patient_rdvs', null, 16],
        "\0".parent::class."\0".'post' => [parent::class, 'post', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        "\0".parent::class."\0".'specialites' => [parent::class, 'specialites', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'telephone_confiance' => [parent::class, 'telephone_confiance', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'date_naissance' => [parent::class, 'date_naissance', null, 16],
        'dossierMedical' => [parent::class, 'dossierMedical', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'genre' => [parent::class, 'genre', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'matricule' => [parent::class, 'matricule', null, 16],
        'medecin_rdvs' => [parent::class, 'medecin_rdvs', null, 16],
        'mes_medecins' => [parent::class, 'mes_medecins', null, 16],
        'mes_patients' => [parent::class, 'mes_patients', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'numero_secu' => [parent::class, 'numero_secu', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'patient_rdvs' => [parent::class, 'patient_rdvs', null, 16],
        'post' => [parent::class, 'post', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
        'specialites' => [parent::class, 'specialites', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'telephone_confiance' => [parent::class, 'telephone_confiance', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
