<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consultation extends \App\Entity\Consultation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'compte_rendu' => [parent::class, 'compte_rendu', null, 16],
        "\0".parent::class."\0".'date_consultation' => [parent::class, 'date_consultation', null, 16],
        "\0".parent::class."\0".'dossierMedical' => [parent::class, 'dossierMedical', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'prescriptions' => [parent::class, 'prescriptions', null, 16],
        'compte_rendu' => [parent::class, 'compte_rendu', null, 16],
        'date_consultation' => [parent::class, 'date_consultation', null, 16],
        'dossierMedical' => [parent::class, 'dossierMedical', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'prescriptions' => [parent::class, 'prescriptions', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
