<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DossierMedical extends \App\Entity\DossierMedical implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'consultations' => [parent::class, 'consultations', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'dossier_patient' => [parent::class, 'dossier_patient', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null, 16],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null, 16],
        "\0".parent::class."\0".'nom_medecin' => [parent::class, 'nom_medecin', null, 16],
        "\0".parent::class."\0".'numero_dossier' => [parent::class, 'numero_dossier', null, 16],
        "\0".parent::class."\0".'observations' => [parent::class, 'observations', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'consultations' => [parent::class, 'consultations', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'dossier_patient' => [parent::class, 'dossier_patient', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'imageFile' => [parent::class, 'imageFile', null, 16],
        'images' => [parent::class, 'images', null, 16],
        'nom_medecin' => [parent::class, 'nom_medecin', null, 16],
        'numero_dossier' => [parent::class, 'numero_dossier', null, 16],
        'observations' => [parent::class, 'observations', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
