<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PS4oLjVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PS4oLjV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PS4oLjV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.PS4oLjV.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator.PS4oLjV": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'image' => 'App\\Entity\\Image',
            'entityManager' => '?',
        ]);
    }
}
