<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ox5DH4LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ox5DH4L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ox5DH4L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'observation' => ['privates', '.errored..service_locator.ox5DH4L.App\\Entity\\Observation', NULL, 'Cannot autowire service ".service_locator.ox5DH4L": it needs an instance of "App\\Entity\\Observation" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'observation' => 'App\\Entity\\Observation',
            'entityManager' => '?',
        ]);
    }
}
