<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nm_.mR6.App\Entity\Consultation' shared service.
     *
     * @return \App\Entity\Consultation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nm_.mR6": it needs an instance of "App\\Entity\\Consultation" but this type has been excluded in "config/services.yaml".');
    }
}
