<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nm_.mR6.App\Controller\ConsultationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.nm_.mR6'] ?? $container->load('get_ServiceLocator_Nm_MR6Service'));

        if (isset($container->privates['.service_locator.nm_.mR6.App\\Controller\\ConsultationController::edit()'])) {
            return $container->privates['.service_locator.nm_.mR6.App\\Controller\\ConsultationController::edit()'];
        }

        return $container->privates['.service_locator.nm_.mR6.App\\Controller\\ConsultationController::edit()'] = $a->withContext('App\\Controller\\ConsultationController::edit()', $container);
    }
}
