<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TWE_Zjz.App\Controller\ConsultationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TWE_Zjz.App\\Controller\\ConsultationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultation' => ['privates', '.errored..service_locator.TWE_Zjz.App\\Entity\\Consultation', NULL, 'Cannot autowire service ".service_locator.TWE_Zjz": it needs an instance of "App\\Entity\\Consultation" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'consultation' => 'App\\Entity\\Consultation',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\ConsultationController::show()', $container);
    }
}
