<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossierMedicalControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6vzoFqy.App\Controller\DossierMedicalController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6vzoFqy.App\\Controller\\DossierMedicalController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossierMedical' => ['privates', '.errored..service_locator.6vzoFqy.App\\Entity\\DossierMedical', NULL, 'Cannot autowire service ".service_locator.6vzoFqy": it needs an instance of "App\\Entity\\DossierMedical" but this type has been excluded in "config/services.yaml".'],
        ], [
            'dossierMedical' => 'App\\Entity\\DossierMedical',
        ]))->withContext('App\\Controller\\DossierMedicalController::show()', $container);
    }
}
