<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossierMedicalControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..2rLAUh.App\Controller\DossierMedicalController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator..2rLAUh'] ?? $container->load('get_ServiceLocator__2rLAUhService'));

        if (isset($container->privates['.service_locator..2rLAUh.App\\Controller\\DossierMedicalController::edit()'])) {
            return $container->privates['.service_locator..2rLAUh.App\\Controller\\DossierMedicalController::edit()'];
        }

        return $container->privates['.service_locator..2rLAUh.App\\Controller\\DossierMedicalController::edit()'] = $a->withContext('App\\Controller\\DossierMedicalController::edit()', $container);
    }
}
