<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.16vKygQ.App\Controller\ImageController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.16vKygQ.App\\Controller\\ImageController::new()'] = ($container->privates['.service_locator.16vKygQ'] ?? $container->load('get_ServiceLocator_16vKygQService'))->withContext('App\\Controller\\ImageController::new()', $container);
    }
}
