<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImage3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gPjv2Im.App\Entity\Image' shared service.
     *
     * @return \App\Entity\Image
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gPjv2Im": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".');
    }
}
