<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyProfilControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WOSBMym.App\Controller\MyProfilController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WOSBMym'] ?? $container->load('get_ServiceLocator_WOSBMymService'));

        if (isset($container->privates['.service_locator.WOSBMym.App\\Controller\\MyProfilController::edit()'])) {
            return $container->privates['.service_locator.WOSBMym.App\\Controller\\MyProfilController::edit()'];
        }

        return $container->privates['.service_locator.WOSBMym.App\\Controller\\MyProfilController::edit()'] = $a->withContext('App\\Controller\\MyProfilController::edit()', $container);
    }
}
