<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObservationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qH_w4.d.App\Controller\ObservationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qH_w4.d.App\\Controller\\ObservationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'observation' => ['privates', '.errored..service_locator.qH_w4.d.App\\Entity\\Observation', NULL, 'Cannot autowire service ".service_locator.qH_w4.d": it needs an instance of "App\\Entity\\Observation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'observation' => 'App\\Entity\\Observation',
        ]))->withContext('App\\Controller\\ObservationController::show()', $container);
    }
}
