<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObservationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ox5DH4L.App\Controller\ObservationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ox5DH4L.App\\Controller\\ObservationController::delete()'] = ($container->privates['.service_locator.ox5DH4L'] ?? $container->load('get_ServiceLocator_Ox5DH4LService'))->withContext('App\\Controller\\ObservationController::delete()', $container);
    }
}
