<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescriptionControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5xkiI7.App\Controller\PrescriptionController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.e5xkiI7'] ?? $container->load('get_ServiceLocator_E5xkiI7Service'));

        if (isset($container->privates['.service_locator.e5xkiI7.App\\Controller\\PrescriptionController::edit()'])) {
            return $container->privates['.service_locator.e5xkiI7.App\\Controller\\PrescriptionController::edit()'];
        }

        return $container->privates['.service_locator.e5xkiI7.App\\Controller\\PrescriptionController::edit()'] = $a->withContext('App\\Controller\\PrescriptionController::edit()', $container);
    }
}
