<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescriptionControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FsyRuId.App\Controller\PrescriptionController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FsyRuId.App\\Controller\\PrescriptionController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'prescription' => ['privates', '.errored..service_locator.FsyRuId.App\\Entity\\Prescription', NULL, 'Cannot autowire service ".service_locator.FsyRuId": it needs an instance of "App\\Entity\\Prescription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'prescription' => 'App\\Entity\\Prescription',
        ]))->withContext('App\\Controller\\PrescriptionController::show()', $container);
    }
}
