<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescriptionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5xkiI7.App\Controller\PrescriptionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e5xkiI7.App\\Controller\\PrescriptionController::delete()'] = ($container->privates['.service_locator.e5xkiI7'] ?? $container->load('get_ServiceLocator_E5xkiI7Service'))->withContext('App\\Controller\\PrescriptionController::delete()', $container);
    }
}
