<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRDVControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mZs_p5g.App\Controller\RDVController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mZs_p5g.App\\Controller\\RDVController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rDV' => ['privates', '.errored..service_locator.mZs_p5g.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.mZs_p5g": it needs an instance of "App\\Entity\\RDV" but this type has been excluded in "config/services.yaml".'],
        ], [
            'rDV' => 'App\\Entity\\RDV',
        ]))->withContext('App\\Controller\\RDVController::show()', $container);
    }
}
