<?php

namespace ContainerQQZfKwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecialiteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Ne3IPD.App\Controller\SpecialiteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Ne3IPD.App\\Controller\\SpecialiteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialite' => ['privates', '.errored..service_locator._Ne3IPD.App\\Entity\\Specialite', NULL, 'Cannot autowire service ".service_locator._Ne3IPD": it needs an instance of "App\\Entity\\Specialite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'specialite' => 'App\\Entity\\Specialite',
        ]))->withContext('App\\Controller\\SpecialiteController::show()', $container);
    }
}
