<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUTyEW7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUTyEW7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGUTyEW7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGUTyEW7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGUTyEW7\App_KernelDevDebugContainer([
    'container.build_hash' => 'GUTyEW7',
    'container.build_id' => '7541f6af',
    'container.build_time' => 1752346348,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUTyEW7');
