<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_mdb-ui-kit_css_mdb_min_css-node_modules_mdb-ui-kit_js_mdb_umd_min_js.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_mdb-ui-kit_css_mdb_min_css-node_modules_mdb-ui-kit_js_mdb_umd_min_js.css',
                '/build/app.css',
            ],
        ],
    ],
],

]];
